export const STEP_SEQUENCE = ['demo', 'do', 'hold', 'relax', 'repeat']

export const movementPlaySession = {
  id: 'movement-play-for-kids',
  title: "Let's Move!",
  subtitle: 'Watch the leader, copy the move, and have fun.',
  boardHeading: "Let's Move!",
  ageRange: 'Ages 6-10',
  productIntent: 'Reusable school wellbeing activity engine',
}

export const movementPlayActivities = [
  {
    id: 'intro',
    label: 'Intro',
    shortLabel: 'Intro',
    boardCue: 'Hello friends',
    icon: 'wave',
    tone: 'calm',
    steps: [
      {
        id: 'greet',
        phaseLabel: 'Intro',
        line: "Hey! Let's move!",
        boardText: "Let's Move!",
        helperText: 'Wave hello and look toward the lead child.',
        durationMs: 2200,
      },
      {
        id: 'ready',
        phaseLabel: 'Ready',
        line: 'Stand up... ready?',
        boardText: 'Stand tall',
        helperText: 'Feet under hips, eyes on the board, ready to start.',
        durationMs: 2600,
      },
    ],
  },
  {
    id: 'armsUp',
    label: 'Arms Up',
    shortLabel: 'Arms Up',
    boardCue: 'Reach high',
    icon: 'arrows-up',
    tone: 'active',
    steps: [
      {
        id: 'demo',
        phaseLabel: 'DEMO',
        line: 'Watch me!',
        boardText: 'Arms Up',
        helperText: 'The lead child shows the motion first.',
        durationMs: 1800,
      },
      {
        id: 'do',
        phaseLabel: 'DO',
        line: 'Hands up!',
        boardText: 'Reach up',
        helperText: 'Stretch both hands gently overhead.',
        durationMs: 2200,
      },
      {
        id: 'hold',
        phaseLabel: 'HOLD',
        line: 'Hold...',
        boardText: 'Stay tall',
        helperText: 'Pause with long arms and steady feet.',
        durationMs: 1800,
      },
      {
        id: 'relax',
        phaseLabel: 'RELAX',
        line: 'Relax down.',
        boardText: 'Lower arms',
        helperText: 'Bring the arms down softly.',
        durationMs: 1900,
      },
      {
        id: 'repeat',
        phaseLabel: 'REPEAT',
        line: 'Again!',
        boardText: 'One more',
        helperText: 'Reset together for another round.',
        durationMs: 1700,
      },
    ],
  },
  {
    id: 'leftStretch',
    label: 'Left Stretch',
    shortLabel: 'Left',
    boardCue: 'Lean gently',
    icon: 'left',
    tone: 'calm',
    steps: [
      {
        id: 'demo',
        phaseLabel: 'DEMO',
        line: 'Watch me!',
        boardText: 'Stretch Left',
        helperText: 'The lead child tilts first so the group can copy.',
        durationMs: 1800,
      },
      {
        id: 'do',
        phaseLabel: 'DO',
        line: 'Lean left!',
        boardText: 'Left side',
        helperText: 'Keep the feet still and lean only a little.',
        durationMs: 2200,
      },
      {
        id: 'hold',
        phaseLabel: 'HOLD',
        line: 'Hold...',
        boardText: 'Stay there',
        helperText: 'Hold the stretch for one calm breath.',
        durationMs: 1800,
      },
      {
        id: 'relax',
        phaseLabel: 'RELAX',
        line: 'Back center.',
        boardText: 'Come back',
        helperText: 'Return to the middle slowly.',
        durationMs: 1900,
      },
      {
        id: 'repeat',
        phaseLabel: 'REPEAT',
        line: 'Nice!',
        boardText: 'Great job',
        helperText: 'A short encouragement keeps the pace light.',
        durationMs: 1700,
      },
    ],
  },
  {
    id: 'rightStretch',
    label: 'Right Stretch',
    shortLabel: 'Right',
    boardCue: 'Switch sides',
    icon: 'right',
    tone: 'calm',
    steps: [
      {
        id: 'demo',
        phaseLabel: 'DEMO',
        line: 'Watch me!',
        boardText: 'Stretch Right',
        helperText: 'The lead child turns attention to the other side.',
        durationMs: 1800,
      },
      {
        id: 'do',
        phaseLabel: 'DO',
        line: 'Lean right!',
        boardText: 'Right side',
        helperText: 'Lean softly right without rushing.',
        durationMs: 2200,
      },
      {
        id: 'hold',
        phaseLabel: 'HOLD',
        line: 'Hold...',
        boardText: 'Stay there',
        helperText: 'Keep the shape steady for a moment.',
        durationMs: 1800,
      },
      {
        id: 'relax',
        phaseLabel: 'RELAX',
        line: 'Back center.',
        boardText: 'Come back',
        helperText: 'Return to center with a calm body.',
        durationMs: 1900,
      },
      {
        id: 'repeat',
        phaseLabel: 'REPEAT',
        line: 'Good!',
        boardText: 'Well done',
        helperText: 'The group finishes the side stretch together.',
        durationMs: 1700,
      },
    ],
  },
  {
    id: 'jump',
    label: 'Light Jump',
    shortLabel: 'Jump',
    boardCue: 'Soft landing',
    icon: 'jump',
    tone: 'active',
    steps: [
      {
        id: 'demo',
        phaseLabel: 'DEMO',
        line: 'Ready?',
        boardText: 'Jump Time',
        helperText: 'The lead child bends the knees to prepare.',
        durationMs: 1700,
      },
      {
        id: 'do',
        phaseLabel: 'DO',
        line: 'Small jumps!',
        boardText: 'Light jumps',
        helperText: 'Everyone makes tiny, easy jumps.',
        durationMs: 2200,
      },
      {
        id: 'hold',
        phaseLabel: 'HOLD',
        line: 'Keep going!',
        boardText: 'Keep rhythm',
        helperText: 'Stay gentle and bouncy without going too high.',
        durationMs: 1900,
      },
      {
        id: 'relax',
        phaseLabel: 'RELAX',
        line: 'Slow down.',
        boardText: 'Slow feet',
        helperText: 'Ease back into stillness.',
        durationMs: 1800,
      },
      {
        id: 'repeat',
        phaseLabel: 'REPEAT',
        line: 'Nice job!',
        boardText: 'You did it',
        helperText: 'Short praise keeps the energy positive.',
        durationMs: 1700,
      },
    ],
  },
  {
    id: 'breathing',
    label: 'Breathing',
    shortLabel: 'Breathe',
    boardCue: 'Slow and steady',
    icon: 'breathing',
    tone: 'calm',
    steps: [
      {
        id: 'demo',
        phaseLabel: 'DEMO',
        line: 'Slow down...',
        boardText: 'Breathing',
        helperText: 'The classroom energy settles before breathing begins.',
        durationMs: 2200,
      },
      {
        id: 'do',
        phaseLabel: 'DO',
        line: 'Breathe in...',
        boardText: 'Inhale',
        helperText: 'Lift the chest a little as the breath comes in.',
        durationMs: 2200,
      },
      {
        id: 'hold',
        phaseLabel: 'HOLD',
        line: 'Hold...',
        boardText: 'Hold',
        helperText: 'Pause gently for a short beat.',
        durationMs: 1800,
      },
      {
        id: 'relax',
        phaseLabel: 'RELAX',
        line: 'Breathe out...',
        boardText: 'Exhale',
        helperText: 'Let the shoulders soften as the air leaves.',
        durationMs: 2200,
      },
      {
        id: 'repeat',
        phaseLabel: 'REPEAT',
        line: 'One more...',
        boardText: 'Once again',
        helperText: 'A final calm cue keeps the rhythm steady.',
        durationMs: 1900,
      },
    ],
  },
  {
    id: 'celebrate',
    label: 'Celebration',
    shortLabel: 'Celebrate',
    boardCue: 'Big smiles',
    icon: 'clap',
    tone: 'joyful',
    steps: [
      {
        id: 'demo',
        phaseLabel: 'DEMO',
        line: 'You did it!',
        boardText: 'Celebrate',
        helperText: 'The session ends with a clear success moment.',
        durationMs: 1800,
      },
      {
        id: 'do',
        phaseLabel: 'DO',
        line: 'Big smile!',
        boardText: 'Smile wide',
        helperText: 'Faces brighten first, then hands come up.',
        durationMs: 1700,
      },
      {
        id: 'hold',
        phaseLabel: 'HOLD',
        line: 'Clap hands!',
        boardText: 'Clap clap',
        helperText: 'A couple of easy claps close the activity.',
        durationMs: 1800,
      },
      {
        id: 'relax',
        phaseLabel: 'RELAX',
        line: 'Happy!',
        boardText: 'Feel proud',
        helperText: 'Let the body soften while the smile stays.',
        durationMs: 1600,
      },
      {
        id: 'repeat',
        phaseLabel: 'REPEAT',
        line: 'Awesome!',
        boardText: 'Awesome!',
        helperText: 'The final cue ends the session on encouragement.',
        durationMs: 1900,
      },
    ],
  },
]
