export const toddlerGuideRiveContract = {
  assetPath: '/rive/toddlerGuide.riv',
  nativeAssetPath: 'assets/rive/toddlerGuide.riv',
  artboard: 'ToddlerGuide',
  stateMachine: 'ToddlerGuideMachine',
  animations: {
    idle: 'idle',
    wave: 'wave',
    clap: 'clap',
    handsUp: 'handsUp',
    jump: 'jump',
    sway: 'sway',
    breathe: 'breathe',
    celebrate: 'celebrate',
  },
  inputs: {
    activityIndex: 'activityIndex',
    isPlaying: 'isPlaying',
    celebrate: 'celebrate',
    calmMode: 'calmMode',
  },
  inputTypes: {
    activityIndex: 'number',
    isPlaying: 'boolean',
    celebrate: 'trigger',
    calmMode: 'boolean',
  },
  activityTriggers: {
    wave: 1,
    clap: 2,
    handsUp: 3,
    jump: 4,
    sway: 5,
    breathe: 6,
  },
  oneShotTriggers: {
    celebrate: 'celebrate',
  },
  expectedLayers: [
    'head_base',
    'eyes',
    'mouth',
    'torso',
    'upper_arm_L',
    'lower_arm_L',
    'hand_L',
    'upper_arm_R',
    'lower_arm_R',
    'hand_R',
    'upper_leg_L',
    'lower_leg_L',
    'foot_L',
    'upper_leg_R',
    'lower_leg_R',
    'foot_R',
  ],
}
